import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1791302623501 implements MigrationInterface {
    name = 'Init1791302623501'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "FamilyMember" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "userId" integer NOT NULL, "role" varchar(191) NOT NULL DEFAULT ('member'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_aee436d2ac963dff186c42d759b" UNIQUE ("familyId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b3c9e23d4f499a9fe4501289f" ON "FamilyMember" ("userId") `);
        await queryRunner.query(`CREATE TABLE "FamilyInvite" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "token" varchar(191) NOT NULL, "createdById" integer NOT NULL, "expiresAt" datetime(3), "revokedAt" datetime(3), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_7da099066a06fffee6db8185c9d" UNIQUE ("token"))`);
        await queryRunner.query(`CREATE INDEX "IDX_519dec9542647a659360ff2f2c" ON "FamilyInvite" ("familyId") `);
        await queryRunner.query(`CREATE TABLE "User" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar(191), "username" varchar(191) NOT NULL, "passwordHash" varchar(191) NOT NULL, "locale" varchar(191) NOT NULL DEFAULT ('zh-CN'), "defaultFamilyId" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_4a257d2c9837248d70640b3e36e" UNIQUE ("email"), CONSTRAINT "UQ_29a05908a0fa0728526d2833657" UNIQUE ("username"))`);
        await queryRunner.query(`CREATE TABLE "Tag" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "color" varchar(191) NOT NULL DEFAULT ('#14b8a6'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_e8403bb80c5d063f00821dd69ac" UNIQUE ("familyId", "name"))`);
        await queryRunner.query(`CREATE TABLE "Template" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "description" varchar(191), "barcode" varchar(191), "imageId" integer, "quantity" integer NOT NULL DEFAULT (1), "price" decimal(12,2) NOT NULL DEFAULT (0), "model" varchar(191), "manufacturer" varchar(191), "defaultLocationId" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_62fc4398ae3f752579d87ffa868" UNIQUE ("familyId", "barcode"))`);
        await queryRunner.query(`CREATE INDEX "IDX_898018e1360e27d31631b41c72" ON "Template" ("familyId", "name") `);
        await queryRunner.query(`CREATE TABLE "ItemUnit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "itemId" integer NOT NULL, "sn" varchar(191), "locationId" integer, "note" varchar(191), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fa576fa527eaa6ecc22d5da0418" UNIQUE ("familyId", "sn"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de9ec71525a37888d490eac861" ON "ItemUnit" ("familyId", "locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aed10fc1e34c6f5759d85825cb" ON "ItemUnit" ("familyId", "itemId") `);
        await queryRunner.query(`CREATE TABLE "Item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "description" varchar(191), "quantity" integer NOT NULL DEFAULT (1), "price" decimal(12,2) NOT NULL DEFAULT (0), "model" varchar(191), "manufacturer" varchar(191), "barcode" varchar(191), "traceCode" varchar(191), "locationId" integer, "templateId" integer, "coverImageId" integer, "qrToken" varchar(191) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fa2fa84b9b741736ecccc5e987a" UNIQUE ("qrToken"), CONSTRAINT "UQ_4a2611b009249881578eb0ba785" UNIQUE ("familyId", "traceCode"), CONSTRAINT "UQ_b6b9f63f8845175370afb8d20b0" UNIQUE ("familyId", "barcode"))`);
        await queryRunner.query(`CREATE INDEX "IDX_79fe46c7a551e4a4c609a4ef7f" ON "Item" ("familyId", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_6530c27b99a7fede3c9903b593" ON "Item" ("familyId", "locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0c71c2a39a41a06ba41d74ed9" ON "Item" ("familyId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "Location" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "parentId" integer, "name" varchar(191) NOT NULL, "description" varchar(191), "imageId" integer, "sortIndex" double NOT NULL DEFAULT (0), "qrToken" varchar(191) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_7d7054854037776b44d977cb63a" UNIQUE ("qrToken"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e6a0c91139990e2062dc22fe9" ON "Location" ("familyId", "parentId", "sortIndex") `);
        await queryRunner.query(`CREATE TABLE "NotificationChannel" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "type" varchar(191) NOT NULL, "name" varchar(191) NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "config" varchar(191) NOT NULL, "events" varchar(191) NOT NULL DEFAULT (''), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_54ba606cb5a5b1a562bc226758" ON "NotificationChannel" ("familyId") `);
        await queryRunner.query(`CREATE TABLE "Family" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(191) NOT NULL, "currency" varchar(191) NOT NULL DEFAULT ('CNY'), "locale" varchar(191) NOT NULL DEFAULT ('zh-CN'), "timeZone" varchar(191) NOT NULL DEFAULT ('Asia/Shanghai'), "isPersonal" boolean NOT NULL DEFAULT (0), "ownerId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "Attachment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "key" varchar(191) NOT NULL, "url" varchar(191), "mime" varchar(191) NOT NULL, "size" integer NOT NULL, "width" integer, "height" integer, "uploadedById" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_62bd618c4503bd1dd3234235b4" ON "Attachment" ("familyId") `);
        await queryRunner.query(`CREATE TABLE "_TemplateTags" ("B" integer NOT NULL, "A" integer NOT NULL, PRIMARY KEY ("B", "A"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c55b9b333e905e1f21439fe7b9" ON "_TemplateTags" ("B") `);
        await queryRunner.query(`CREATE INDEX "IDX_446ebfca56f5d9b9bce20a49f9" ON "_TemplateTags" ("A") `);
        await queryRunner.query(`CREATE TABLE "_ItemImages" ("B" integer NOT NULL, "A" integer NOT NULL, PRIMARY KEY ("B", "A"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14a6bcef5571dbbab26a7301d2" ON "_ItemImages" ("B") `);
        await queryRunner.query(`CREATE INDEX "IDX_d90e9591251b2a43ed1b485bc1" ON "_ItemImages" ("A") `);
        await queryRunner.query(`CREATE TABLE "_ItemTags" ("A" integer NOT NULL, "B" integer NOT NULL, PRIMARY KEY ("A", "B"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ddff1474545a4a78386ee982a" ON "_ItemTags" ("A") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2cf303c77cec519f0bc677153" ON "_ItemTags" ("B") `);
        await queryRunner.query(`DROP INDEX "IDX_1b3c9e23d4f499a9fe4501289f"`);
        await queryRunner.query(`CREATE TABLE "temporary_FamilyMember" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "userId" integer NOT NULL, "role" varchar(191) NOT NULL DEFAULT ('member'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_aee436d2ac963dff186c42d759b" UNIQUE ("familyId", "userId"), CONSTRAINT "FK_2d069a8ccc6f8270c523f4af4e9" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_1b3c9e23d4f499a9fe4501289f2" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_FamilyMember"("id", "familyId", "userId", "role", "createdAt") SELECT "id", "familyId", "userId", "role", "createdAt" FROM "FamilyMember"`);
        await queryRunner.query(`DROP TABLE "FamilyMember"`);
        await queryRunner.query(`ALTER TABLE "temporary_FamilyMember" RENAME TO "FamilyMember"`);
        await queryRunner.query(`CREATE INDEX "IDX_1b3c9e23d4f499a9fe4501289f" ON "FamilyMember" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_519dec9542647a659360ff2f2c"`);
        await queryRunner.query(`CREATE TABLE "temporary_FamilyInvite" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "token" varchar(191) NOT NULL, "createdById" integer NOT NULL, "expiresAt" datetime(3), "revokedAt" datetime(3), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_7da099066a06fffee6db8185c9d" UNIQUE ("token"), CONSTRAINT "FK_519dec9542647a659360ff2f2c6" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_aee74c7c75da1a8dd9ad750ef8e" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_FamilyInvite"("id", "familyId", "token", "createdById", "expiresAt", "revokedAt", "createdAt") SELECT "id", "familyId", "token", "createdById", "expiresAt", "revokedAt", "createdAt" FROM "FamilyInvite"`);
        await queryRunner.query(`DROP TABLE "FamilyInvite"`);
        await queryRunner.query(`ALTER TABLE "temporary_FamilyInvite" RENAME TO "FamilyInvite"`);
        await queryRunner.query(`CREATE INDEX "IDX_519dec9542647a659360ff2f2c" ON "FamilyInvite" ("familyId") `);
        await queryRunner.query(`CREATE TABLE "temporary_User" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar(191), "username" varchar(191) NOT NULL, "passwordHash" varchar(191) NOT NULL, "locale" varchar(191) NOT NULL DEFAULT ('zh-CN'), "defaultFamilyId" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_4a257d2c9837248d70640b3e36e" UNIQUE ("email"), CONSTRAINT "UQ_29a05908a0fa0728526d2833657" UNIQUE ("username"), CONSTRAINT "FK_d9cacc0fba2ab08bfb9c9f53860" FOREIGN KEY ("defaultFamilyId") REFERENCES "Family" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_User"("id", "email", "username", "passwordHash", "locale", "defaultFamilyId", "createdAt", "updatedAt") SELECT "id", "email", "username", "passwordHash", "locale", "defaultFamilyId", "createdAt", "updatedAt" FROM "User"`);
        await queryRunner.query(`DROP TABLE "User"`);
        await queryRunner.query(`ALTER TABLE "temporary_User" RENAME TO "User"`);
        await queryRunner.query(`CREATE TABLE "temporary_Tag" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "color" varchar(191) NOT NULL DEFAULT ('#14b8a6'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_e8403bb80c5d063f00821dd69ac" UNIQUE ("familyId", "name"), CONSTRAINT "FK_3b203bc9fd1bed686cc632a3866" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Tag"("id", "familyId", "name", "color", "createdAt") SELECT "id", "familyId", "name", "color", "createdAt" FROM "Tag"`);
        await queryRunner.query(`DROP TABLE "Tag"`);
        await queryRunner.query(`ALTER TABLE "temporary_Tag" RENAME TO "Tag"`);
        await queryRunner.query(`DROP INDEX "IDX_898018e1360e27d31631b41c72"`);
        await queryRunner.query(`CREATE TABLE "temporary_Template" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "description" varchar(191), "barcode" varchar(191), "imageId" integer, "quantity" integer NOT NULL DEFAULT (1), "price" decimal(12,2) NOT NULL DEFAULT (0), "model" varchar(191), "manufacturer" varchar(191), "defaultLocationId" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_62fc4398ae3f752579d87ffa868" UNIQUE ("familyId", "barcode"), CONSTRAINT "FK_8e51d60558f7ecb3c7433365819" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_2ed84f7bdfd7ba3a8155f2ac603" FOREIGN KEY ("imageId") REFERENCES "Attachment" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_443fa753f7ca346084fc73df2a6" FOREIGN KEY ("defaultLocationId") REFERENCES "Location" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Template"("id", "familyId", "name", "description", "barcode", "imageId", "quantity", "price", "model", "manufacturer", "defaultLocationId", "createdAt", "updatedAt") SELECT "id", "familyId", "name", "description", "barcode", "imageId", "quantity", "price", "model", "manufacturer", "defaultLocationId", "createdAt", "updatedAt" FROM "Template"`);
        await queryRunner.query(`DROP TABLE "Template"`);
        await queryRunner.query(`ALTER TABLE "temporary_Template" RENAME TO "Template"`);
        await queryRunner.query(`CREATE INDEX "IDX_898018e1360e27d31631b41c72" ON "Template" ("familyId", "name") `);
        await queryRunner.query(`DROP INDEX "IDX_de9ec71525a37888d490eac861"`);
        await queryRunner.query(`DROP INDEX "IDX_aed10fc1e34c6f5759d85825cb"`);
        await queryRunner.query(`CREATE TABLE "temporary_ItemUnit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "itemId" integer NOT NULL, "sn" varchar(191), "locationId" integer, "note" varchar(191), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fa576fa527eaa6ecc22d5da0418" UNIQUE ("familyId", "sn"), CONSTRAINT "FK_2ef0429378cc894460ee853f71b" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b3f0a0ad87d66cae87be0598190" FOREIGN KEY ("itemId") REFERENCES "Item" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_092ddadb955739d43e33f3150ea" FOREIGN KEY ("locationId") REFERENCES "Location" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ItemUnit"("id", "familyId", "itemId", "sn", "locationId", "note", "createdAt", "updatedAt") SELECT "id", "familyId", "itemId", "sn", "locationId", "note", "createdAt", "updatedAt" FROM "ItemUnit"`);
        await queryRunner.query(`DROP TABLE "ItemUnit"`);
        await queryRunner.query(`ALTER TABLE "temporary_ItemUnit" RENAME TO "ItemUnit"`);
        await queryRunner.query(`CREATE INDEX "IDX_de9ec71525a37888d490eac861" ON "ItemUnit" ("familyId", "locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aed10fc1e34c6f5759d85825cb" ON "ItemUnit" ("familyId", "itemId") `);
        await queryRunner.query(`DROP INDEX "IDX_79fe46c7a551e4a4c609a4ef7f"`);
        await queryRunner.query(`DROP INDEX "IDX_6530c27b99a7fede3c9903b593"`);
        await queryRunner.query(`DROP INDEX "IDX_b0c71c2a39a41a06ba41d74ed9"`);
        await queryRunner.query(`CREATE TABLE "temporary_Item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "description" varchar(191), "quantity" integer NOT NULL DEFAULT (1), "price" decimal(12,2) NOT NULL DEFAULT (0), "model" varchar(191), "manufacturer" varchar(191), "barcode" varchar(191), "traceCode" varchar(191), "locationId" integer, "templateId" integer, "coverImageId" integer, "qrToken" varchar(191) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fa2fa84b9b741736ecccc5e987a" UNIQUE ("qrToken"), CONSTRAINT "UQ_4a2611b009249881578eb0ba785" UNIQUE ("familyId", "traceCode"), CONSTRAINT "UQ_b6b9f63f8845175370afb8d20b0" UNIQUE ("familyId", "barcode"), CONSTRAINT "FK_2dee3a9141240f1c5706119e696" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_81bfd2a470f786abd1babac44cc" FOREIGN KEY ("locationId") REFERENCES "Location" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_68d05b97558cbad80482e6444f6" FOREIGN KEY ("templateId") REFERENCES "Template" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_294bd17c7561a6319da5b69a619" FOREIGN KEY ("coverImageId") REFERENCES "Attachment" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Item"("id", "familyId", "name", "description", "quantity", "price", "model", "manufacturer", "barcode", "traceCode", "locationId", "templateId", "coverImageId", "qrToken", "createdAt", "updatedAt") SELECT "id", "familyId", "name", "description", "quantity", "price", "model", "manufacturer", "barcode", "traceCode", "locationId", "templateId", "coverImageId", "qrToken", "createdAt", "updatedAt" FROM "Item"`);
        await queryRunner.query(`DROP TABLE "Item"`);
        await queryRunner.query(`ALTER TABLE "temporary_Item" RENAME TO "Item"`);
        await queryRunner.query(`CREATE INDEX "IDX_79fe46c7a551e4a4c609a4ef7f" ON "Item" ("familyId", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_6530c27b99a7fede3c9903b593" ON "Item" ("familyId", "locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0c71c2a39a41a06ba41d74ed9" ON "Item" ("familyId", "createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_4e6a0c91139990e2062dc22fe9"`);
        await queryRunner.query(`CREATE TABLE "temporary_Location" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "parentId" integer, "name" varchar(191) NOT NULL, "description" varchar(191), "imageId" integer, "sortIndex" double NOT NULL DEFAULT (0), "qrToken" varchar(191) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_7d7054854037776b44d977cb63a" UNIQUE ("qrToken"), CONSTRAINT "FK_a75c9398272a7a71b738cc3a8c8" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_65556fcd36c96e3f8385a7df6de" FOREIGN KEY ("parentId") REFERENCES "Location" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_05edf5d8bf6368727b022c3ef1e" FOREIGN KEY ("imageId") REFERENCES "Attachment" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Location"("id", "familyId", "parentId", "name", "description", "imageId", "sortIndex", "qrToken", "createdAt", "updatedAt") SELECT "id", "familyId", "parentId", "name", "description", "imageId", "sortIndex", "qrToken", "createdAt", "updatedAt" FROM "Location"`);
        await queryRunner.query(`DROP TABLE "Location"`);
        await queryRunner.query(`ALTER TABLE "temporary_Location" RENAME TO "Location"`);
        await queryRunner.query(`CREATE INDEX "IDX_4e6a0c91139990e2062dc22fe9" ON "Location" ("familyId", "parentId", "sortIndex") `);
        await queryRunner.query(`DROP INDEX "IDX_54ba606cb5a5b1a562bc226758"`);
        await queryRunner.query(`CREATE TABLE "temporary_NotificationChannel" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "type" varchar(191) NOT NULL, "name" varchar(191) NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "config" varchar(191) NOT NULL, "events" varchar(191) NOT NULL DEFAULT (''), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_54ba606cb5a5b1a562bc2267580" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_NotificationChannel"("id", "familyId", "type", "name", "enabled", "config", "events", "createdAt", "updatedAt") SELECT "id", "familyId", "type", "name", "enabled", "config", "events", "createdAt", "updatedAt" FROM "NotificationChannel"`);
        await queryRunner.query(`DROP TABLE "NotificationChannel"`);
        await queryRunner.query(`ALTER TABLE "temporary_NotificationChannel" RENAME TO "NotificationChannel"`);
        await queryRunner.query(`CREATE INDEX "IDX_54ba606cb5a5b1a562bc226758" ON "NotificationChannel" ("familyId") `);
        await queryRunner.query(`CREATE TABLE "temporary_Family" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(191) NOT NULL, "currency" varchar(191) NOT NULL DEFAULT ('CNY'), "locale" varchar(191) NOT NULL DEFAULT ('zh-CN'), "timeZone" varchar(191) NOT NULL DEFAULT ('Asia/Shanghai'), "isPersonal" boolean NOT NULL DEFAULT (0), "ownerId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_a2080d57eda956cac073803ac1f" FOREIGN KEY ("ownerId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Family"("id", "name", "currency", "locale", "timeZone", "isPersonal", "ownerId", "createdAt", "updatedAt") SELECT "id", "name", "currency", "locale", "timeZone", "isPersonal", "ownerId", "createdAt", "updatedAt" FROM "Family"`);
        await queryRunner.query(`DROP TABLE "Family"`);
        await queryRunner.query(`ALTER TABLE "temporary_Family" RENAME TO "Family"`);
        await queryRunner.query(`DROP INDEX "IDX_62bd618c4503bd1dd3234235b4"`);
        await queryRunner.query(`CREATE TABLE "temporary_Attachment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "key" varchar(191) NOT NULL, "url" varchar(191), "mime" varchar(191) NOT NULL, "size" integer NOT NULL, "width" integer, "height" integer, "uploadedById" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_62bd618c4503bd1dd3234235b41" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_27a322b7a8c9dc19335ed2f18ce" FOREIGN KEY ("uploadedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Attachment"("id", "familyId", "key", "url", "mime", "size", "width", "height", "uploadedById", "createdAt") SELECT "id", "familyId", "key", "url", "mime", "size", "width", "height", "uploadedById", "createdAt" FROM "Attachment"`);
        await queryRunner.query(`DROP TABLE "Attachment"`);
        await queryRunner.query(`ALTER TABLE "temporary_Attachment" RENAME TO "Attachment"`);
        await queryRunner.query(`CREATE INDEX "IDX_62bd618c4503bd1dd3234235b4" ON "Attachment" ("familyId") `);
        await queryRunner.query(`DROP INDEX "IDX_c55b9b333e905e1f21439fe7b9"`);
        await queryRunner.query(`DROP INDEX "IDX_446ebfca56f5d9b9bce20a49f9"`);
        await queryRunner.query(`CREATE TABLE "temporary__TemplateTags" ("B" integer NOT NULL, "A" integer NOT NULL, CONSTRAINT "FK_c55b9b333e905e1f21439fe7b9c" FOREIGN KEY ("B") REFERENCES "Template" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_446ebfca56f5d9b9bce20a49f90" FOREIGN KEY ("A") REFERENCES "Tag" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("B", "A"))`);
        await queryRunner.query(`INSERT INTO "temporary__TemplateTags"("B", "A") SELECT "B", "A" FROM "_TemplateTags"`);
        await queryRunner.query(`DROP TABLE "_TemplateTags"`);
        await queryRunner.query(`ALTER TABLE "temporary__TemplateTags" RENAME TO "_TemplateTags"`);
        await queryRunner.query(`CREATE INDEX "IDX_c55b9b333e905e1f21439fe7b9" ON "_TemplateTags" ("B") `);
        await queryRunner.query(`CREATE INDEX "IDX_446ebfca56f5d9b9bce20a49f9" ON "_TemplateTags" ("A") `);
        await queryRunner.query(`DROP INDEX "IDX_14a6bcef5571dbbab26a7301d2"`);
        await queryRunner.query(`DROP INDEX "IDX_d90e9591251b2a43ed1b485bc1"`);
        await queryRunner.query(`CREATE TABLE "temporary__ItemImages" ("B" integer NOT NULL, "A" integer NOT NULL, CONSTRAINT "FK_14a6bcef5571dbbab26a7301d20" FOREIGN KEY ("B") REFERENCES "Item" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_d90e9591251b2a43ed1b485bc1b" FOREIGN KEY ("A") REFERENCES "Attachment" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("B", "A"))`);
        await queryRunner.query(`INSERT INTO "temporary__ItemImages"("B", "A") SELECT "B", "A" FROM "_ItemImages"`);
        await queryRunner.query(`DROP TABLE "_ItemImages"`);
        await queryRunner.query(`ALTER TABLE "temporary__ItemImages" RENAME TO "_ItemImages"`);
        await queryRunner.query(`CREATE INDEX "IDX_14a6bcef5571dbbab26a7301d2" ON "_ItemImages" ("B") `);
        await queryRunner.query(`CREATE INDEX "IDX_d90e9591251b2a43ed1b485bc1" ON "_ItemImages" ("A") `);
        await queryRunner.query(`DROP INDEX "IDX_4ddff1474545a4a78386ee982a"`);
        await queryRunner.query(`DROP INDEX "IDX_c2cf303c77cec519f0bc677153"`);
        await queryRunner.query(`CREATE TABLE "temporary__ItemTags" ("A" integer NOT NULL, "B" integer NOT NULL, CONSTRAINT "FK_4ddff1474545a4a78386ee982a7" FOREIGN KEY ("A") REFERENCES "Item" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_c2cf303c77cec519f0bc677153c" FOREIGN KEY ("B") REFERENCES "Tag" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("A", "B"))`);
        await queryRunner.query(`INSERT INTO "temporary__ItemTags"("A", "B") SELECT "A", "B" FROM "_ItemTags"`);
        await queryRunner.query(`DROP TABLE "_ItemTags"`);
        await queryRunner.query(`ALTER TABLE "temporary__ItemTags" RENAME TO "_ItemTags"`);
        await queryRunner.query(`CREATE INDEX "IDX_4ddff1474545a4a78386ee982a" ON "_ItemTags" ("A") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2cf303c77cec519f0bc677153" ON "_ItemTags" ("B") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_c2cf303c77cec519f0bc677153"`);
        await queryRunner.query(`DROP INDEX "IDX_4ddff1474545a4a78386ee982a"`);
        await queryRunner.query(`ALTER TABLE "_ItemTags" RENAME TO "temporary__ItemTags"`);
        await queryRunner.query(`CREATE TABLE "_ItemTags" ("A" integer NOT NULL, "B" integer NOT NULL, PRIMARY KEY ("A", "B"))`);
        await queryRunner.query(`INSERT INTO "_ItemTags"("A", "B") SELECT "A", "B" FROM "temporary__ItemTags"`);
        await queryRunner.query(`DROP TABLE "temporary__ItemTags"`);
        await queryRunner.query(`CREATE INDEX "IDX_c2cf303c77cec519f0bc677153" ON "_ItemTags" ("B") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ddff1474545a4a78386ee982a" ON "_ItemTags" ("A") `);
        await queryRunner.query(`DROP INDEX "IDX_d90e9591251b2a43ed1b485bc1"`);
        await queryRunner.query(`DROP INDEX "IDX_14a6bcef5571dbbab26a7301d2"`);
        await queryRunner.query(`ALTER TABLE "_ItemImages" RENAME TO "temporary__ItemImages"`);
        await queryRunner.query(`CREATE TABLE "_ItemImages" ("B" integer NOT NULL, "A" integer NOT NULL, PRIMARY KEY ("B", "A"))`);
        await queryRunner.query(`INSERT INTO "_ItemImages"("B", "A") SELECT "B", "A" FROM "temporary__ItemImages"`);
        await queryRunner.query(`DROP TABLE "temporary__ItemImages"`);
        await queryRunner.query(`CREATE INDEX "IDX_d90e9591251b2a43ed1b485bc1" ON "_ItemImages" ("A") `);
        await queryRunner.query(`CREATE INDEX "IDX_14a6bcef5571dbbab26a7301d2" ON "_ItemImages" ("B") `);
        await queryRunner.query(`DROP INDEX "IDX_446ebfca56f5d9b9bce20a49f9"`);
        await queryRunner.query(`DROP INDEX "IDX_c55b9b333e905e1f21439fe7b9"`);
        await queryRunner.query(`ALTER TABLE "_TemplateTags" RENAME TO "temporary__TemplateTags"`);
        await queryRunner.query(`CREATE TABLE "_TemplateTags" ("B" integer NOT NULL, "A" integer NOT NULL, PRIMARY KEY ("B", "A"))`);
        await queryRunner.query(`INSERT INTO "_TemplateTags"("B", "A") SELECT "B", "A" FROM "temporary__TemplateTags"`);
        await queryRunner.query(`DROP TABLE "temporary__TemplateTags"`);
        await queryRunner.query(`CREATE INDEX "IDX_446ebfca56f5d9b9bce20a49f9" ON "_TemplateTags" ("A") `);
        await queryRunner.query(`CREATE INDEX "IDX_c55b9b333e905e1f21439fe7b9" ON "_TemplateTags" ("B") `);
        await queryRunner.query(`DROP INDEX "IDX_62bd618c4503bd1dd3234235b4"`);
        await queryRunner.query(`ALTER TABLE "Attachment" RENAME TO "temporary_Attachment"`);
        await queryRunner.query(`CREATE TABLE "Attachment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "key" varchar(191) NOT NULL, "url" varchar(191), "mime" varchar(191) NOT NULL, "size" integer NOT NULL, "width" integer, "height" integer, "uploadedById" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "Attachment"("id", "familyId", "key", "url", "mime", "size", "width", "height", "uploadedById", "createdAt") SELECT "id", "familyId", "key", "url", "mime", "size", "width", "height", "uploadedById", "createdAt" FROM "temporary_Attachment"`);
        await queryRunner.query(`DROP TABLE "temporary_Attachment"`);
        await queryRunner.query(`CREATE INDEX "IDX_62bd618c4503bd1dd3234235b4" ON "Attachment" ("familyId") `);
        await queryRunner.query(`ALTER TABLE "Family" RENAME TO "temporary_Family"`);
        await queryRunner.query(`CREATE TABLE "Family" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(191) NOT NULL, "currency" varchar(191) NOT NULL DEFAULT ('CNY'), "locale" varchar(191) NOT NULL DEFAULT ('zh-CN'), "timeZone" varchar(191) NOT NULL DEFAULT ('Asia/Shanghai'), "isPersonal" boolean NOT NULL DEFAULT (0), "ownerId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "Family"("id", "name", "currency", "locale", "timeZone", "isPersonal", "ownerId", "createdAt", "updatedAt") SELECT "id", "name", "currency", "locale", "timeZone", "isPersonal", "ownerId", "createdAt", "updatedAt" FROM "temporary_Family"`);
        await queryRunner.query(`DROP TABLE "temporary_Family"`);
        await queryRunner.query(`DROP INDEX "IDX_54ba606cb5a5b1a562bc226758"`);
        await queryRunner.query(`ALTER TABLE "NotificationChannel" RENAME TO "temporary_NotificationChannel"`);
        await queryRunner.query(`CREATE TABLE "NotificationChannel" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "type" varchar(191) NOT NULL, "name" varchar(191) NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "config" varchar(191) NOT NULL, "events" varchar(191) NOT NULL DEFAULT (''), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "NotificationChannel"("id", "familyId", "type", "name", "enabled", "config", "events", "createdAt", "updatedAt") SELECT "id", "familyId", "type", "name", "enabled", "config", "events", "createdAt", "updatedAt" FROM "temporary_NotificationChannel"`);
        await queryRunner.query(`DROP TABLE "temporary_NotificationChannel"`);
        await queryRunner.query(`CREATE INDEX "IDX_54ba606cb5a5b1a562bc226758" ON "NotificationChannel" ("familyId") `);
        await queryRunner.query(`DROP INDEX "IDX_4e6a0c91139990e2062dc22fe9"`);
        await queryRunner.query(`ALTER TABLE "Location" RENAME TO "temporary_Location"`);
        await queryRunner.query(`CREATE TABLE "Location" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "parentId" integer, "name" varchar(191) NOT NULL, "description" varchar(191), "imageId" integer, "sortIndex" double NOT NULL DEFAULT (0), "qrToken" varchar(191) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_7d7054854037776b44d977cb63a" UNIQUE ("qrToken"))`);
        await queryRunner.query(`INSERT INTO "Location"("id", "familyId", "parentId", "name", "description", "imageId", "sortIndex", "qrToken", "createdAt", "updatedAt") SELECT "id", "familyId", "parentId", "name", "description", "imageId", "sortIndex", "qrToken", "createdAt", "updatedAt" FROM "temporary_Location"`);
        await queryRunner.query(`DROP TABLE "temporary_Location"`);
        await queryRunner.query(`CREATE INDEX "IDX_4e6a0c91139990e2062dc22fe9" ON "Location" ("familyId", "parentId", "sortIndex") `);
        await queryRunner.query(`DROP INDEX "IDX_b0c71c2a39a41a06ba41d74ed9"`);
        await queryRunner.query(`DROP INDEX "IDX_6530c27b99a7fede3c9903b593"`);
        await queryRunner.query(`DROP INDEX "IDX_79fe46c7a551e4a4c609a4ef7f"`);
        await queryRunner.query(`ALTER TABLE "Item" RENAME TO "temporary_Item"`);
        await queryRunner.query(`CREATE TABLE "Item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "description" varchar(191), "quantity" integer NOT NULL DEFAULT (1), "price" decimal(12,2) NOT NULL DEFAULT (0), "model" varchar(191), "manufacturer" varchar(191), "barcode" varchar(191), "traceCode" varchar(191), "locationId" integer, "templateId" integer, "coverImageId" integer, "qrToken" varchar(191) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fa2fa84b9b741736ecccc5e987a" UNIQUE ("qrToken"), CONSTRAINT "UQ_4a2611b009249881578eb0ba785" UNIQUE ("familyId", "traceCode"), CONSTRAINT "UQ_b6b9f63f8845175370afb8d20b0" UNIQUE ("familyId", "barcode"))`);
        await queryRunner.query(`INSERT INTO "Item"("id", "familyId", "name", "description", "quantity", "price", "model", "manufacturer", "barcode", "traceCode", "locationId", "templateId", "coverImageId", "qrToken", "createdAt", "updatedAt") SELECT "id", "familyId", "name", "description", "quantity", "price", "model", "manufacturer", "barcode", "traceCode", "locationId", "templateId", "coverImageId", "qrToken", "createdAt", "updatedAt" FROM "temporary_Item"`);
        await queryRunner.query(`DROP TABLE "temporary_Item"`);
        await queryRunner.query(`CREATE INDEX "IDX_b0c71c2a39a41a06ba41d74ed9" ON "Item" ("familyId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6530c27b99a7fede3c9903b593" ON "Item" ("familyId", "locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_79fe46c7a551e4a4c609a4ef7f" ON "Item" ("familyId", "name") `);
        await queryRunner.query(`DROP INDEX "IDX_aed10fc1e34c6f5759d85825cb"`);
        await queryRunner.query(`DROP INDEX "IDX_de9ec71525a37888d490eac861"`);
        await queryRunner.query(`ALTER TABLE "ItemUnit" RENAME TO "temporary_ItemUnit"`);
        await queryRunner.query(`CREATE TABLE "ItemUnit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "itemId" integer NOT NULL, "sn" varchar(191), "locationId" integer, "note" varchar(191), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fa576fa527eaa6ecc22d5da0418" UNIQUE ("familyId", "sn"))`);
        await queryRunner.query(`INSERT INTO "ItemUnit"("id", "familyId", "itemId", "sn", "locationId", "note", "createdAt", "updatedAt") SELECT "id", "familyId", "itemId", "sn", "locationId", "note", "createdAt", "updatedAt" FROM "temporary_ItemUnit"`);
        await queryRunner.query(`DROP TABLE "temporary_ItemUnit"`);
        await queryRunner.query(`CREATE INDEX "IDX_aed10fc1e34c6f5759d85825cb" ON "ItemUnit" ("familyId", "itemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_de9ec71525a37888d490eac861" ON "ItemUnit" ("familyId", "locationId") `);
        await queryRunner.query(`DROP INDEX "IDX_898018e1360e27d31631b41c72"`);
        await queryRunner.query(`ALTER TABLE "Template" RENAME TO "temporary_Template"`);
        await queryRunner.query(`CREATE TABLE "Template" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "description" varchar(191), "barcode" varchar(191), "imageId" integer, "quantity" integer NOT NULL DEFAULT (1), "price" decimal(12,2) NOT NULL DEFAULT (0), "model" varchar(191), "manufacturer" varchar(191), "defaultLocationId" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_62fc4398ae3f752579d87ffa868" UNIQUE ("familyId", "barcode"))`);
        await queryRunner.query(`INSERT INTO "Template"("id", "familyId", "name", "description", "barcode", "imageId", "quantity", "price", "model", "manufacturer", "defaultLocationId", "createdAt", "updatedAt") SELECT "id", "familyId", "name", "description", "barcode", "imageId", "quantity", "price", "model", "manufacturer", "defaultLocationId", "createdAt", "updatedAt" FROM "temporary_Template"`);
        await queryRunner.query(`DROP TABLE "temporary_Template"`);
        await queryRunner.query(`CREATE INDEX "IDX_898018e1360e27d31631b41c72" ON "Template" ("familyId", "name") `);
        await queryRunner.query(`ALTER TABLE "Tag" RENAME TO "temporary_Tag"`);
        await queryRunner.query(`CREATE TABLE "Tag" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "name" varchar(191) NOT NULL, "color" varchar(191) NOT NULL DEFAULT ('#14b8a6'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_e8403bb80c5d063f00821dd69ac" UNIQUE ("familyId", "name"))`);
        await queryRunner.query(`INSERT INTO "Tag"("id", "familyId", "name", "color", "createdAt") SELECT "id", "familyId", "name", "color", "createdAt" FROM "temporary_Tag"`);
        await queryRunner.query(`DROP TABLE "temporary_Tag"`);
        await queryRunner.query(`ALTER TABLE "User" RENAME TO "temporary_User"`);
        await queryRunner.query(`CREATE TABLE "User" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar(191), "username" varchar(191) NOT NULL, "passwordHash" varchar(191) NOT NULL, "locale" varchar(191) NOT NULL DEFAULT ('zh-CN'), "defaultFamilyId" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_4a257d2c9837248d70640b3e36e" UNIQUE ("email"), CONSTRAINT "UQ_29a05908a0fa0728526d2833657" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "User"("id", "email", "username", "passwordHash", "locale", "defaultFamilyId", "createdAt", "updatedAt") SELECT "id", "email", "username", "passwordHash", "locale", "defaultFamilyId", "createdAt", "updatedAt" FROM "temporary_User"`);
        await queryRunner.query(`DROP TABLE "temporary_User"`);
        await queryRunner.query(`DROP INDEX "IDX_519dec9542647a659360ff2f2c"`);
        await queryRunner.query(`ALTER TABLE "FamilyInvite" RENAME TO "temporary_FamilyInvite"`);
        await queryRunner.query(`CREATE TABLE "FamilyInvite" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "token" varchar(191) NOT NULL, "createdById" integer NOT NULL, "expiresAt" datetime(3), "revokedAt" datetime(3), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_7da099066a06fffee6db8185c9d" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "FamilyInvite"("id", "familyId", "token", "createdById", "expiresAt", "revokedAt", "createdAt") SELECT "id", "familyId", "token", "createdById", "expiresAt", "revokedAt", "createdAt" FROM "temporary_FamilyInvite"`);
        await queryRunner.query(`DROP TABLE "temporary_FamilyInvite"`);
        await queryRunner.query(`CREATE INDEX "IDX_519dec9542647a659360ff2f2c" ON "FamilyInvite" ("familyId") `);
        await queryRunner.query(`DROP INDEX "IDX_1b3c9e23d4f499a9fe4501289f"`);
        await queryRunner.query(`ALTER TABLE "FamilyMember" RENAME TO "temporary_FamilyMember"`);
        await queryRunner.query(`CREATE TABLE "FamilyMember" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "familyId" integer NOT NULL, "userId" integer NOT NULL, "role" varchar(191) NOT NULL DEFAULT ('member'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_aee436d2ac963dff186c42d759b" UNIQUE ("familyId", "userId"))`);
        await queryRunner.query(`INSERT INTO "FamilyMember"("id", "familyId", "userId", "role", "createdAt") SELECT "id", "familyId", "userId", "role", "createdAt" FROM "temporary_FamilyMember"`);
        await queryRunner.query(`DROP TABLE "temporary_FamilyMember"`);
        await queryRunner.query(`CREATE INDEX "IDX_1b3c9e23d4f499a9fe4501289f" ON "FamilyMember" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_c2cf303c77cec519f0bc677153"`);
        await queryRunner.query(`DROP INDEX "IDX_4ddff1474545a4a78386ee982a"`);
        await queryRunner.query(`DROP TABLE "_ItemTags"`);
        await queryRunner.query(`DROP INDEX "IDX_d90e9591251b2a43ed1b485bc1"`);
        await queryRunner.query(`DROP INDEX "IDX_14a6bcef5571dbbab26a7301d2"`);
        await queryRunner.query(`DROP TABLE "_ItemImages"`);
        await queryRunner.query(`DROP INDEX "IDX_446ebfca56f5d9b9bce20a49f9"`);
        await queryRunner.query(`DROP INDEX "IDX_c55b9b333e905e1f21439fe7b9"`);
        await queryRunner.query(`DROP TABLE "_TemplateTags"`);
        await queryRunner.query(`DROP INDEX "IDX_62bd618c4503bd1dd3234235b4"`);
        await queryRunner.query(`DROP TABLE "Attachment"`);
        await queryRunner.query(`DROP TABLE "Family"`);
        await queryRunner.query(`DROP INDEX "IDX_54ba606cb5a5b1a562bc226758"`);
        await queryRunner.query(`DROP TABLE "NotificationChannel"`);
        await queryRunner.query(`DROP INDEX "IDX_4e6a0c91139990e2062dc22fe9"`);
        await queryRunner.query(`DROP TABLE "Location"`);
        await queryRunner.query(`DROP INDEX "IDX_b0c71c2a39a41a06ba41d74ed9"`);
        await queryRunner.query(`DROP INDEX "IDX_6530c27b99a7fede3c9903b593"`);
        await queryRunner.query(`DROP INDEX "IDX_79fe46c7a551e4a4c609a4ef7f"`);
        await queryRunner.query(`DROP TABLE "Item"`);
        await queryRunner.query(`DROP INDEX "IDX_aed10fc1e34c6f5759d85825cb"`);
        await queryRunner.query(`DROP INDEX "IDX_de9ec71525a37888d490eac861"`);
        await queryRunner.query(`DROP TABLE "ItemUnit"`);
        await queryRunner.query(`DROP INDEX "IDX_898018e1360e27d31631b41c72"`);
        await queryRunner.query(`DROP TABLE "Template"`);
        await queryRunner.query(`DROP TABLE "Tag"`);
        await queryRunner.query(`DROP TABLE "User"`);
        await queryRunner.query(`DROP INDEX "IDX_519dec9542647a659360ff2f2c"`);
        await queryRunner.query(`DROP TABLE "FamilyInvite"`);
        await queryRunner.query(`DROP INDEX "IDX_1b3c9e23d4f499a9fe4501289f"`);
        await queryRunner.query(`DROP TABLE "FamilyMember"`);
    }

}
